on: [push]
name: AzureARMStorage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.ANIL_SECRET_CRED }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: nestrg
        template: ./templatevn.json
